import { type NextPage } from "next";
import Head from "next/head";
import { PieChart } from "../components/PieChart/PieChart";

const habits = [
  { name: "Meditate", daysCompleted: 1 },
  { name: "Go for a run", daysCompleted: 2 },
  { name: "Drawing", daysCompleted: 3 },
  { name: "Connect", daysCompleted: 4 },
  { name: "Make bed", daysCompleted: 5 },
  { name: "Plan life", daysCompleted: 6 },
  { name: "Code", daysCompleted: 7 },
  { name: "Eat Healthy", daysCompleted: 7 },
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-[#10015c] p-8 text-sm text-white">
        <article className="mx-auto grid max-w-[1000px] grid-cols-4 gap-4 rounded-sm border border-indigo-700 bg-[#12006b] p-4">
          {habits.map(({ name, daysCompleted }) => (
            <section
              key={name}
              className="flex justify-between rounded-sm bg-indigo-900 p-4"
            >
              <PieChart progress={(daysCompleted / 7) * 100} />
              <section>
                <h1 className="text-base">{name}:</h1>
                <p>
                  <span className="font-semibold text-pink-600">
                    {daysCompleted}
                  </span>{" "}
                  out of <span className="font-semibold text-pink-600">7</span>
                </p>
              </section>
            </section>
          ))}
        </article>
      </main>
    </>
  );
};

export default Home;
